### ISSUE TITLE
Floor dimensions

### ISSUE THREAD

**Issue by atesgoral** [atesgoral/hrm-level-data#10]
It could be useful to record the floor rows + columns so that:
1. Floor max idx can be checked for program validity
2. Potential tools that attempt to recreate the level layout (hrm-cpu visual debug mode?)

Perhaps we can extend the floor property to be an object:

```
floor: {
    rows: 5,
    columns: 5,
    tiles: [ ] / {}
}
```

**Comment by nrkn** [comment]
:+1: 

I'm not doing _any_ error checking at all on the source files atm, I just assume that they're valid - it should at the very least enforce the floor size

**Comment by nrkn** [comment]
I'm good with the above schema btw, let's do it

**Comment by atesgoral** [comment]
Sure!

**Comment by atesgoral** [comment]
1cf6241d6f258b9650dde03166ab7cd9725c3cbd

Still need to populate rows and columns.
