### ISSUE TITLE
Not enough tests

### ISSUE THREAD

**Issue by nrkn** [atesgoral/hrm-level-data#4]
Each level only has one set of expected input/output at the moment (in in-progress branch)

**Comment by atesgoral** [comment]
I'll take a look if I can tap into the game's binary to extract level data.

**Comment by atesgoral** [comment]
I did take a look at the binary. I managed to extract what I think the bulk of the program is by using a PE unpacker. But then I didn't see any immediate signs of plain strings (e.g. level names). The thing looks compressed. I don't think I'll pursue data extraction. We'll have to manually enter some sample data.

**Comment by atesgoral** [comment]
Or maybe this repo should be renamed to hrm-level-metadata and just be about level info + setup. I've started https://github.com/atesgoral/hrm-level-io-generator for programmatic generation of an infinite number of inbox/outbox pairs.

**Comment by nrkn** [comment]
Woah, that's awesome

**Comment by atesgoral** [comment]
I decided to split that into two projects: One for generating input, one for computing the output for a given input. Still working on it :)

**Comment by atesgoral** [comment]
https://github.com/atesgoral/hrm-level-inbox-generator
https://github.com/atesgoral/hrm-level-outbox-generator

Trying to finish the outbox generators first.

**Comment by nrkn** [comment]
Cool, I've got quite a bit to do on cpu, but looking forward to playing with it. Would be great to test more thoroughly

Also on that note, I'm trying to figure out what the best way to get all the solutions from your solutions project into a json for testing - to pull them from github programatically so I can always test with up to date versions, or just take a static copy or... any ideas?

**Comment by atesgoral** [comment]
I'm planning to add a build step to generate JSON to publish a mini-website on gh-pages. You should be able to grab the JSON once that's done.

**Comment by nrkn** [comment]
:+1:

**Comment by atesgoral** [comment]
The inbox and outbox generators are now complete and published on NPM.

**Comment by nrkn** [comment]
Awesome!
