### ISSUE TITLE
Poor formatting

### ISSUE THREAD

**Issue by nrkn** [atesgoral/hrm-level-data#5]
I really don't like the default JSON.stringify treatment of arrays in the in-progress branch, would be better if they were like this:

``` json
[ 1, 2, 3 ]
```

**Comment by atesgoral** [comment]
Due to the lack of my knowledge of any JSON formatters that output actual human-readable JSON, I'm writing a script to "manually" reformat the JSON.

**Comment by atesgoral** [comment]
A rudimentary formatter.js added for the time being. Closing.

**Comment by nrkn** [comment]
Wow, you did so much while I was asleep! Awesome work.

I added a formatter, it uses default JSON.stringify behaviour for the most part, just overriding simple arrays
