### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by nrkn** [atesgoral/hrm-level-data#9]
Please :)

**Comment by atesgoral** [comment]
I think you should be allowed to publish as well. I had added you to as a contributor on npmjs.org.

**Comment by nrkn** [comment]
OK, I'll bump the version number and see if I can

**Comment by nrkn** [comment]
:+1:

**Comment by atesgoral** [comment]
:+1: 

I guess we'll bump the major version to 1.0.0 once the content is complete/stable.

**Comment by nrkn** [comment]
Cool I'm going to update the hrm-cpu tests to use this now

**Comment by atesgoral** [comment]
Awesome! :) I'm already using hrm-cpu for CI: https://travis-ci.org/atesgoral/human-resource-machine-solutions (It's not set to fail the tests yet, since hrm-cpu is choking on some of the solutions).

**Comment by nrkn** [comment]
Yeah that'll probably be the later levels that I haven't played yet - not bumping hrm-cpu to 1.0.0 until it passes for all levels
